{% set name = "eo-learn-geometry" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 780aff2f1e3d0a6f0780f2aef88c524d9aafb3288602367a8a48e3d305aed450

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [(win and vc<14) or py<35]

requirements:
  host:
    - pip
    - python
  run:
    - descartes
    - eo-learn-core
    - geopandas
    - python
    - rasterio
    - scikit-image >=0.15.0
    - shapely
    - pillow
    - dataclasses

test:
  imports:
    - eolearn
    - eolearn.geometry

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of geometry utilities and EOTasks
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.geometry.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - dcunn
    - oblute
    - rluria14
    - benhuff
